#spring:
 # thymeleaf:
  #  prefix: classpath:/templates/
   # suffix: .html

spring:
  #freemarker:
  #  enabled: true
  #  charset: UTF-8
  #  content-type: text/html
  #  template-loader-path: classpath:/templates/
  #  suffix: .ftl
  datasource:
    test1:
        jdbcurl: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        minPoolSize: 3
        maxPoolSize: 25
        maxLifetime: 20000
        borrowConnectionTimeout: 30
        loginTimeout: 30
        maintenanceInterval: 60
        maxIdleTime: 60
        testQuery: select 1

    test2:
        jdbcurl: jdbc:mysql://localhost:3306/test2
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        minPoolSize: 3
        maxPoolSize: 25
        maxLifetime: 20000
        borrowConnectionTimeout: 30
        loginTimeout: 30
        maintenanceInterval: 60
        maxIdleTime: 60
        testQuery: select 1

  redis:
      password:   #Redis服务器连接密码（默认为空）
      host: 127.0.0.1
      port: 6379  #Redis服务器连接端口
      timeout: 30000      #连接超时时间（毫秒）
      jedis:
          pool:
              max-active: 8   #连接池最大连接数（使用负值表示没有限制）
              max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 8     #连接池中的最大空闲连接
              min-idle: 0     #连接池中的最小空闲连接

logging:
    config: classpath:log4j2.yml
